// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgshmykmloemktajpjdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnc2hteWttbG9lbWt0YWpwamRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTE5NTIsImV4cCI6MjA1NjE4Nzk1Mn0._ilxNJ9lN2oDKRZXj2GklL8CRIiCd6GG7ER9vjzGnXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);